### ISSUE TITLE
Streams auth method deprecation warning

### ISSUE THREAD

**Issue by chrism2671** [jrusso1020/alpaca_elixir#24]
Currently works fine, but expect this to break in due course. Will try to open a PR if I get a chance.

```
20:03:34.172 [warning] AlpacaStreamClient Received a message: %{"data" => %{"action" => "authenticate", "message" => "this authentication format is being deprecated. Please use the format: {\"action\": \"auth\", \"key\": \"x\", \"secret\": \"x\"}", "status" => "authorized"}, "stream" => "authorization"}
20:03:34.251 [warning] Hedger.AlpacaStreamClient Received a message: %{"data" => %{"streams" => []}, "stream" => "listening"}
```

**Comment by jrusso1020** [comment]
Thanks for opening the issue @chrism2671 feel free to open up a PR and we can try and get it merged! if not I'll see if I can try and fix it sometime soonish

**Comment by jrusso1020** [comment]
I think this should be fixed now by https://github.com/jrusso1020/alpaca_elixir/pull/25
